sonar.projectKey=ParkingAllotment
sonar.working.directory=C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\.sonar
sonar.projectBaseDir=C:\\MySoleraCodes\\ParkingAllocationBackend
sonar.pullrequest.cache.basepath=C:\\MySoleraCodes\\ParkingAllocationBackend

33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.projectKey=ParkingAllotment:33691C50-5B8B-4DF1-98D8-E558B980D172
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.projectName=ParkingAllocationBackend
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.projectBaseDir=C:\\MySoleraCodes\\ParkingAllocationBackend
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.sourceEncoding=utf-8
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.tests=
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.sources=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Auth\\IJwtTokenGenerator.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Auth\\JwtTokenGenerator.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\BackgroundServices\\ExpiredAllocationChecker.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Controllers\\AuthController.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Controllers\\ParkingAllocationController.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Controllers\\ParkingSpaceController.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Controllers\\UserController.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Controllers\\VehicleController.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Data\\ApplicationDbContext.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\CreateParkingAllocationDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\CreateVehicleDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\GetAllVehicleDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\LoginDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\ParkingAllocationDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\ParkingSpaceDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\RegisterDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\UserDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\DTO\\VehicleDto.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250726193029_InitialCreate.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250726193029_InitialCreate.Designer.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802052732_MakeVehicleIdNullableAndSetNullOnDelete.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802052732_MakeVehicleIdNullableAndSetNullOnDelete.Designer.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802054806_create.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802054806_create.Designer.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802055100_MakeVehicleIdNullableAndSetNullOnDeleteV2.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802055100_MakeVehicleIdNullableAndSetNullOnDeleteV2.Designer.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802055349_MakeVehicleIdNullableAndSetNullOnDeleteV3.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802055349_MakeVehicleIdNullableAndSetNullOnDeleteV3.Designer.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802055752_new.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\20250802055752_new.Designer.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Migrations\\ApplicationDbContextModelSnapshot.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Models\\ParkingAllocation.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Models\\ParkingSpace.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Models\\User.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Models\\Vehicle.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Program.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Implementations\\AuthService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Implementations\\ParkingAllocationService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Implementations\\ParkingSpaceService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Implementations\\UserService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Implementations\\VehicleService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Interfaces\\IAuthService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Interfaces\\IParkingAllocationService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Interfaces\\IParkingSpaceService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Interfaces\\IUserService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Services\\Interfaces\\IVehicleService.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\ParkingAllocationBackend.GlobalUsings.g.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\.NETCoreApp,Version=v8.0.AssemblyAttributes.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\ParkingAllocationBackend.AssemblyInfo.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\ParkingAllocationBackend.MvcApplicationPartsAssemblyInfo.cs",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\appsettings.Development.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\appsettings.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\appsettings.template.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.gitignore",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\ParkingAllocationBackend.http",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\Properties\\launchSettings.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\ParkingAllocationBackend.csproj.nuget.dgspec.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\project.assets.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.vs\\ParkingAllocationBackend\\config\\applicationhost.config",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.vs\\ParkingAllocationBackend\\v17\\DocumentLayout.backup.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.vs\\ParkingAllocationBackend\\v17\\DocumentLayout.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\bin\\Debug\\net8.0\\appsettings.Development.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\bin\\Debug\\net8.0\\appsettings.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\bin\\Debug\\net8.0\\appsettings.template.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\bin\\Debug\\net8.0\\ParkingAllocationBackend.deps.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\bin\\Debug\\net8.0\\ParkingAllocationBackend.runtimeconfig.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\bin\\Debug\\net8.0\\ParkingAllocationBackend.staticwebassets.endpoints.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\ApiEndpoints.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\rjsmcshtml.dswa.cache.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\rjsmrazor.dswa.cache.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\rpswa.dswa.cache.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\staticwebassets.build.endpoints.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\staticwebassets.build.json",\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\obj\\Debug\\net8.0\\EndpointInfo\\ParkingAllocationBackend.json"

33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.cs.analyzer.projectOutPaths=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\0"
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.cs.roslyn.reportFilePaths=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\0\\Issues.json"
33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.cs.scanner.telemetry=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\0\\Telemetry.json"

33691C50-5B8B-4DF1-98D8-E558B980D172.sonar.working.directory=C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\.sonar\\mod0
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.projectKey=ParkingAllotment:6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.projectName=ParkingAllocationBackend.Tests
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.projectBaseDir=C:\\MySoleraCodes\\ParkingAllocationBackend.Tests
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.sourceEncoding=utf-8
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.sources=
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.tests=\


6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.cs.analyzer.projectOutPaths=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\1"
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.cs.roslyn.reportFilePaths=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\1\\Issues.json"
6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.cs.scanner.telemetry=\
"C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\1\\Telemetry.json"

6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6.sonar.working.directory=C:\\MySoleraCodes\\ParkingAllocationBackend\\.sonarqube\\out\\.sonar\\mod1
sonar.host.url=http://localhost:9000
sonar.visualstudio.enable=false

sonar.modules=33691C50-5B8B-4DF1-98D8-E558B980D172,6B4EF4AF-0DB0-4F3B-A7D2-5BFD26CFA2A6

